<Table style="width:65%" id="tblRunTicker" class="w3-table w3-striped w3-border w3-bordered w3-centered"><TR class="w3-white" ALIGN="center" VALIGN="middle"><TD colspan=6><FONT FACE="Arial" SIZE=+1><B>Run Ticker</B></tr><TR class="w3-gray" ALIGN="center" VALIGN="middle"><TD><FONT FACE="Arial" SIZE=+1><B>TIME</B></FONT></TD><TD><FONT FACE="Arial" SIZE=+1><B>CAR/CLASS</B></FONT></TD><TD><FONT FACE="Arial" SIZE=+1><B>NAME</B></FONT></TD><TD><FONT FACE="Arial" SIZE=+1><B>RUN #</B></FONT></TD><TD><FONT FACE="Arial" SIZE=+1><B>TIME</B></FONT></TD></TR>
<TR VALIGN="bottom"><TD ALIGN="center"><FONT FACE="Arial">08/22/2020 14:06:08</FONT></TD><TD ALIGN="center"><FONT FACE="Arial"><A HREF="Z.php">999 Z</A></FONT></TD><TD ALIGN="center"><FONT FACE="Arial"></FONT></TD><TD ALIGN="center"><FONT FACE="Arial">41</FONT></TD><TD ALIGN="center"><FONT FACE="Arial">39.963</FONT></TD></TR>
<TR VALIGN="bottom"><TD ALIGN="center"><FONT FACE="Arial">08/22/2020 14:05:54</FONT></TD><TD ALIGN="center"><FONT FACE="Arial"><A HREF="Z.php">999 Z</A></FONT></TD><TD ALIGN="center"><FONT FACE="Arial"></FONT></TD><TD ALIGN="center"><FONT FACE="Arial">40</FONT></TD><TD ALIGN="center"><FONT FACE="Arial">58.751</FONT></TD></TR>
<TR VALIGN="bottom"><TD ALIGN="center"><FONT FACE="Arial">08/22/2020 14:05:54</FONT></TD><TD ALIGN="center"><FONT FACE="Arial"><A HREF="Z.php">999 Z</A></FONT></TD><TD ALIGN="center"><FONT FACE="Arial"></FONT></TD><TD ALIGN="center"><FONT FACE="Arial">40</FONT></TD><TD ALIGN="center"><FONT FACE="Arial">58.751</FONT></TD></TR>
<TR VALIGN="bottom"><TD ALIGN="center"><FONT FACE="Arial">08/22/2020 13:41:44</FONT></TD><TD ALIGN="center"><FONT FACE="Arial"><A HREF="FSP.php">19 FSP</A></FONT></TD><TD ALIGN="center"><FONT FACE="Arial">Lucas Jones</FONT></TD><TD ALIGN="center"><FONT FACE="Arial">16</FONT></TD><TD ALIGN="center"><FONT FACE="Arial">54.124</FONT></TD></TR>
<TR VALIGN="bottom"><TD ALIGN="center"><FONT FACE="Arial">08/22/2020 13:41:00</FONT></TD><TD ALIGN="center"><FONT FACE="Arial"><A HREF="GS.php">556 GS</A></FONT></TD><TD ALIGN="center"><FONT FACE="Arial">Bradley James</FONT></TD><TD ALIGN="center"><FONT FACE="Arial">18</FONT></TD><TD ALIGN="center"><FONT FACE="Arial">48.245</FONT></TD></TR>
<TR VALIGN="bottom"><TD ALIGN="center"><FONT FACE="Arial">08/22/2020 13:40:25</FONT></TD><TD ALIGN="center"><FONT FACE="Arial"><A HREF="CM.php">78 CM</A></FONT></TD><TD ALIGN="center"><FONT FACE="Arial">Joel Harleman</FONT></TD><TD ALIGN="center"><FONT FACE="Arial">1</FONT></TD><TD ALIGN="center"><FONT FACE="Arial">39.691</FONT></TD></TR>

</Table>
