<Table style="width:65%" id="tblRunTicker" class="w3-table w3-striped w3-border w3-bordered w3-centered"><TR class="w3-white" ALIGN="center" VALIGN="middle"><TD colspan=6><FONT FACE="Arial" SIZE=+1><B>Run Ticker</B></tr><TR class="w3-gray" ALIGN="center" VALIGN="middle"><TD><FONT FACE="Arial" SIZE=+1><B>TIME</B></FONT></TD><TD><FONT FACE="Arial" SIZE=+1><B>CAR/CLASS</B></FONT></TD><TD><FONT FACE="Arial" SIZE=+1><B>NAME</B></FONT></TD><TD><FONT FACE="Arial" SIZE=+1><B>RUN #</B></FONT></TD><TD><FONT FACE="Arial" SIZE=+1><B>TIME</B></FONT></TD></TR>
<TR VALIGN="bottom"><TD ALIGN="center"><FONT FACE="Arial">06/28/2020 10:09:13</FONT></TD><TD ALIGN="center"><FONT FACE="Arial"><A HREF="DS.php">105 DS</A></FONT></TD><TD ALIGN="center"><FONT FACE="Arial">Nathan Bierrum</FONT></TD><TD ALIGN="center"><FONT FACE="Arial">1</FONT></TD><TD ALIGN="center"><FONT FACE="Arial">66.736</FONT></TD></TR>
<TR VALIGN="bottom"><TD ALIGN="center"><FONT FACE="Arial">06/28/2020 10:08:52</FONT></TD><TD ALIGN="center"><FONT FACE="Arial"><A HREF="DS.php">24 DS</A></FONT></TD><TD ALIGN="center"><FONT FACE="Arial">Nicole Khan</FONT></TD><TD ALIGN="center"><FONT FACE="Arial">1</FONT></TD><TD ALIGN="center"><FONT FACE="Arial">66.292</FONT></TD></TR>
<TR VALIGN="bottom"><TD ALIGN="center"><FONT FACE="Arial">06/28/2020 10:08:21</FONT></TD><TD ALIGN="center"><FONT FACE="Arial"><A HREF="DS.php">46 DS</A></FONT></TD><TD ALIGN="center"><FONT FACE="Arial">Douglas Smiley</FONT></TD><TD ALIGN="center"><FONT FACE="Arial">1</FONT></TD><TD ALIGN="center"><FONT FACE="Arial">55.443</FONT></TD></TR>
<TR VALIGN="bottom"><TD ALIGN="center"><FONT FACE="Arial">06/28/2020 10:07:57</FONT></TD><TD ALIGN="center"><FONT FACE="Arial"><A HREF="STX.php">16 STX</A></FONT></TD><TD ALIGN="center"><FONT FACE="Arial">Brian Britten</FONT></TD><TD ALIGN="center"><FONT FACE="Arial">1</FONT></TD><TD ALIGN="center"><FONT FACE="Arial">50.270 +1</FONT></TD></TR>
<TR VALIGN="bottom"><TD ALIGN="center"><FONT FACE="Arial">06/28/2020 10:07:47</FONT></TD><TD ALIGN="center"><FONT FACE="Arial"><A HREF="DS.php">44 DS</A></FONT></TD><TD ALIGN="center"><FONT FACE="Arial">Jake White</FONT></TD><TD ALIGN="center"><FONT FACE="Arial">1</FONT></TD><TD ALIGN="center"><FONT FACE="Arial">59.828</FONT></TD></TR>
<TR VALIGN="bottom"><TD ALIGN="center"><FONT FACE="Arial">06/28/2020 10:07:22</FONT></TD><TD ALIGN="center"><FONT FACE="Arial"><A HREF="DS.php">81 DS</A></FONT></TD><TD ALIGN="center"><FONT FACE="Arial">Lee Miller</FONT></TD><TD ALIGN="center"><FONT FACE="Arial">1</FONT></TD><TD ALIGN="center"><FONT FACE="Arial">55.335</FONT></TD></TR>

</Table>
