APPLY_FIXES: none
ENABLE:
  - CSS
  - HTML
  - PHP
CSS_STYLELINT_ARGUMENTS: --no-color
HTML_HTMLHINT_ARGUMENTS: --nocolor
PHP_PSALM_ARGUMENTS: -m

CONFIG_REPORTER: false
UPDATED_SOURCES_REPORTER: false