APPLY_FIXES: none
CLEAR_REPORT_FOLDER: true

ENABLE:
  - COPYPASTE
  # - CSS
  # - HTML
  # - PHP
  - REPOSITORY

ENABLE_LINTERS:
  - "CSS_STYLELINT"
  - "HTML_HTMLHINT"
  - "JAVASCRIPT_ES"
  - "PHP_PHPCS"
  - "PHP_PHPLINT"
  - "PHP_PSALM"
  - "PHP_PHPSTAN"

EXCLUDED_DIRECTORIES:
  - "files"
  - "vendor"

COPYPASTE_JSCPD_DISABLE_ERRORS: true

CSS_STYLELINT_ARGUMENTS:
  - "--no-color"

HTML_HTMLHINT_ARGUMENTS:
  - "--nocolor"

PHP_PSALM_ARGUMENTS: -m

# CONFIG_REPORTER: false
UPDATED_SOURCES_REPORTER: false
